### PR TITLE
smallBeautification

### PR DESCRIPTION
**Pull request by jmnietsch**
- Added Values to Branch Selection
- Disable Development Phase in any "Agile" Project

### CODE REVIEW

**Comment by allabors** [comment]
image
  at braches i see that. should it be like this?

**Comment by allabors** [comment]
image

and for "classic" dev proccess i can not also choose phase

**Comment by jmnietsch** [comment]
No idea, why that happened... It works fine with me.
Can you specify what you did? I could not reproduce the Problem while typing in the same values.

**Comment by maielgendy** [comment]
same with me ... project phase is disabled i just clicked on the new project , changed the development process to classic

**Comment by jmnietsch** [comment]
Ok. Then ignore it for the moment.
I will recheck it and I have even found another bug (one that I actually can reproduce).

**Pull request closed without merging**
